services:
  db:
    image: postgres:16
    container_name: imdb_postgres
    restart: always
    environment:
      POSTGRES_USER: imdbuser
      POSTGRES_PASSWORD: imdbpass
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./dataset:/dataset

  frontend:
    build: ./frontend
    container_name: imdb_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build: ./api
    container_name: imdb_api
    restart: always
    environment:
      POSTGRES_USER: imdbuser
      POSTGRES_PASSWORD: imdbpass
      POSTGRES_DB: imdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: imdb_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@imdb.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_servers.json:/pgadmin4/servers.json

volumes:
  pgadmin_data:
